default_platform(:ios)

platform :ios do
  desc "Build IPA file"
  lane :build do

	match(type: "appstore", app_identifier: ["com.xailabs.varusschlacht"]	)  
  sync_code_signing
  cert
  sigh

  enable_automatic_code_signing(path: "/tmp/ios/Unity-iPhone.xcodeproj")

	build_app(
    project: "/tmp/ios/Unity-iPhone.xcodeproj",
	  include_symbols: false,
	  include_bitcode: false,
	  export_method: "ad-hoc",
	  output_directory: "/tmp/ios/dist/",
	  output_name: "app.ipa",
		xcargs: "-allowProvisioningUpdates"
	)
  end  
end